-- MySQL Script generated by MySQL Workbench
-- 12/03/16 12:04:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Conference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conference` (
  `idConference` INT NOT NULL,
  `conferenceName` VARCHAR(100) NOT NULL,
  `timeStart` TIMESTAMP(6) NULL,
  `timeEnd` TIMESTAMP(6) NULL,
  PRIMARY KEY (`idConference`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Session` (
  `idSession` INT NOT NULL,
  `sessionName` VARCHAR(45) NULL,
  `timeStart` TIMESTAMP(6) NULL,
  `timeEnd` TIMESTAMP(6) NULL,
  `sessionType` VARCHAR(1) NULL,
  `idConference` INT NULL,
  PRIMARY KEY (`idSession`),
  UNIQUE INDEX `idSession_UNIQUE` (`idSession` ASC),
  INDEX `idConference_idx` (`idConference` ASC),
  CONSTRAINT `idConference`
    FOREIGN KEY (`idConference`)
    REFERENCES `mydb`.`Conference` (`idConference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Speaker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Speaker` (
  `idSpeaker` INT NOT NULL,
  `firstAndSecondName` VARCHAR(100) NOT NULL,
  `arrivalDate` TIMESTAMP(6) NOT NULL,
  `departureDate` TIMESTAMP(6) NOT NULL,
  `idConference` INT NOT NULL,
  PRIMARY KEY (`idSpeaker`),
  UNIQUE INDEX `idSpeaker_UNIQUE` (`idSpeaker` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lecture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lecture` (
  `idLecture` INT NOT NULL,
  `lectureName` VARCHAR(45) NULL,
  `idSpeaker` INT NULL,
  `idSession` INT NULL,
  `lectureType` VARCHAR(1) NULL,
  `thema` VARCHAR(100) NULL,
  `abstract` VARCHAR(300) NULL,
  `kw1` INT NULL,
  `kw2` INT NULL,
  `kw3` INT NULL,
  `idConference` INT NULL,
  UNIQUE INDEX `idLecture_UNIQUE` (`idLecture` ASC),
  PRIMARY KEY (`idLecture`),
  INDEX `idSession_idx` (`idSession` ASC),
  INDEX `idSpeaker_idx` (`idSpeaker` ASC),
  CONSTRAINT `idSession`
    FOREIGN KEY (`idSession`)
    REFERENCES `mydb`.`Session` (`idSession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSpeaker`
    FOREIGN KEY (`idSpeaker`)
    REFERENCES `mydb`.`Speaker` (`idSpeaker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL,
  `userName` VARCHAR(100) NULL,
  `userPassword` VARCHAR(100) NULL,
  `userMail` VARCHAR(100) NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `mydb`.`conference` (`idConference`, `conferenceName`, `timeStart`, `timeEnd`) VALUES ('0', '1', '2013-10-06 16:00:00', '2013-10-06 16:00:00');
ALTER TABLE `mydb`.`lecture` 
ADD COLUMN `numberIn` INT(11) NULL AFTER `idConference`;
ALTER TABLE `mydb`.`users` 
DROP COLUMN `idUsers`,
CHANGE COLUMN `userName` `userName` VARCHAR(100) NOT NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`userName`);

ALTER TABLE `mydb`.`lecture` 
CHANGE COLUMN `idConference` `idConference` INT(11) NOT NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`idLecture`, `idConference`);

ALTER TABLE `mydb`.`session` 
DROP FOREIGN KEY `idConference`;
ALTER TABLE `mydb`.`session` 
CHANGE COLUMN `idConference` `idConference` INT(11) NOT NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`idSession`, `idConference`);
ALTER TABLE `mydb`.`session` 
ADD CONSTRAINT `idConference`
  FOREIGN KEY (`idConference`)
  REFERENCES `mydb`.`conference` (`idConference`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
ALTER TABLE `mydb`.`speaker` 
DROP PRIMARY KEY,
ADD PRIMARY KEY (`idSpeaker`, `idConference`);
